registry:
  docker:
    name: registry2
    image: registry:2
    tag: latest
    ports:
      - "5000:5000"
    binds:
      - "/etc/registry/data/config.yml:/etc/docker/registry/config.yml:ro"
      - "/etc/registry/data:/var/lib/registry:ro"
      - "/etc/registry/certs:/certs:ro"
      - "/etc/registry/auth:/auth:ro"
  env:
    - ENV=DEBUG

  settings:
    log:
      accesslog:
        disabled: false
      level: debug
      formatter: text
      fields:
        service: registry
        environment: development
      # hooks:
      #   - type: mail
      #     disabled: true
      #     levels:
      #       - panic
      #     options:
      #       smtp:
      #         addr: mail.example.com:25
      #         username: mailuser
      #         password: password
      #         insecure: true
      #       from: sender@example.com
      #       to:
      #         - errors@example.com
    http:
      secret: asecret
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    storage:
      # filesystem:
      #   rootdirectory: /var/lib/registry
      #   maxthreads: 100
      s3:
        accesskey: AKIAIMH5BJVNSQQO2AYQ
        secretkey: 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
        region: eu-west-1
        # regionendpoint: http://myobjects.local
        bucket: dev-chute
        # encrypt: true
        # keyid: mykeyid
        # secure: true
        v4auth: true
        chunksize: 5242880
        multipartcopychunksize: 33554432
        multipartcopymaxconcurrency: 100
        multipartcopythresholdsize: 33554432
        rootdirectory: /docker-registry
      delete:
        enabled: false
      redirect:
        disable: false
      # cache:
      #   blobdescriptor: redis
      maintenance:
        uploadpurging:
          enabled: true
          age: 168h
          interval: 24h
          dryrun: false
        readonly:
          enabled: false
    auth:
      # silly:
      #   realm: silly-realm
      #   service: silly-service
      # token:
      #   realm: token-realm
      #   service: token-service
      #   issuer: registry-token-issuer
      #   rootcertbundle: /root/certs/bundle
      htpasswd:
        realm: basic-realm
        path: /path/to/htpasswd
    notifications:
      endpoints:
        - name: registry events
          url: http://localhost:8000/event
          # headers:
          #   Authorization: [Bearer <your token, if needed>]
          timeout: 500ms
          threshold: 5
          backoff: 1s